### ISSUE TITLE
Home Assistant 2023.5.0 Error initializing

### ISSUE THREAD

**Issue by axcs** [netsoft-ruidias/ha-custom-component-myedenred#6]
Hello, this component has always worked without problems, at the moment with the Home Assistant 2023.5.0 update, it stopped working and has this error displayed. I already removed the account and installed it again and it didn't work
![ed](https://user-images.githubusercontent.com/5928308/236075376-d387a858-cdef-4393-ba83-affd8fff29f6.png)

**Comment by andre-g-rodrigues** [comment]
Same problem here.
`Este erro teve origem numa integração personalizada.

Logger: homeassistant.config_entries
Source: custom_components/myedenred/__init__.py:27
Integration: MyEdenred Cartão Refeição (documentation, issues)
First occurred: 10:02:12 (5 occurrences)
Last logged: 14:16:50

Error setting up entry MyEdenred xxx@gmail.com for myedenred
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myedenred/__init__.py", line 27, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
`

**Comment by netsoft-ruidias** [comment]
Fixed in version v1.1.1
